"""Curated Voice Agent Integration Catalog (29 Verified & Active Business Tools).

All 29 integrations are enabled and verified in Nango.
"""
from typing import Any

CATALOG_INTEGRATIONS: list[dict[str, Any]] = [
    # --- 1. SCHEDULING & CALENDARS (LIVE IN-CALL) ---
    {
        "id": "GOOGLECALENDAR",
        "name": "Google Calendar",
        "category": "Scheduling",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "oauth",
        "description": "Check live calendar availability, book meetings, and reschedule appointments during voice calls.",
        "actions": ["Find Free Slots", "Create Booking", "Reschedule Event"],
        "badge": "Popular",
        "iconName": "Calendar",
        "color": "text-sky-500 bg-sky-500/10",
    },
    {
        "id": "CALENDLY",
        "name": "Calendly",
        "category": "Scheduling",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "oauth",
        "description": "Query available event types, check invitee schedules, and trigger Calendly booking links.",
        "actions": ["Get Event Types", "Check Availability", "Cancel Event"],
        "badge": "Popular",
        "iconName": "Calendar",
        "color": "text-sky-500 bg-sky-500/10",
    },
    {
        "id": "CALCOM",
        "name": "Cal.com",
        "category": "Scheduling",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "oauth",
        "description": "Real-time calendar booking and availability slot queries directly synced to Cal.com schedules.",
        "actions": ["Find Available Slots", "Book Booking", "Cancel Booking"],
        "badge": "Fast",
        "iconName": "Calendar",
        "color": "text-sky-500 bg-sky-500/10",
    },
    {
        "id": "ZOOM",
        "name": "Zoom Meetings",
        "category": "Scheduling",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "oauth",
        "description": "Generate unique Zoom video meeting links and passwords instantly for caller appointments.",
        "actions": ["Create Meeting", "Get Meeting Details", "List Recordings"],
        "badge": "Video",
        "iconName": "Video",
        "color": "text-blue-500 bg-blue-500/10",
    },

    # --- 2. CRM & SALES (IN-CALL & POST-CALL) ---
    {
        "id": "HUBSPOT",
        "name": "HubSpot CRM",
        "category": "CRM",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "oauth",
        "description": "Instant caller contact lookup, create CRM leads, and log call outcomes to deals in real time.",
        "actions": ["Lookup Contact", "Create Lead", "Update Deal Stage"],
        "badge": "Popular",
        "iconName": "Database",
        "color": "text-orange-500 bg-orange-500/10",
    },
    {
        "id": "SALESFORCE",
        "name": "Salesforce",
        "category": "CRM",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "oauth",
        "description": "Enterprise CRM lookup, log voice call activities, and update pipeline stages during or after calls.",
        "actions": ["Search Accounts", "Create Lead / Opportunity", "Log Call Activity"],
        "badge": "Enterprise",
        "iconName": "Database",
        "color": "text-blue-600 bg-blue-600/10",
    },

    # --- 3. CUSTOMER SUPPORT & HELPDESK ---
    {
        "id": "ZENDESK",
        "name": "Zendesk Support",
        "category": "Support",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "oauth",
        "description": "Look up open support tickets by phone number and create priority support tickets live on calls.",
        "actions": ["Lookup Tickets by Phone", "Create Ticket", "Update Ticket Status"],
        "badge": "Popular",
        "iconName": "LifeBuoy",
        "color": "text-emerald-600 bg-emerald-600/10",
    },
    {
        "id": "INTERCOM",
        "name": "Intercom",
        "category": "Support",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "oauth",
        "description": "Search customer profiles, check conversation histories, and log incoming phone call notes.",
        "actions": ["Search Contact", "Create Ticket", "Add Conversation Note"],
        "badge": "Support",
        "iconName": "MessageSquare",
        "color": "text-blue-500 bg-blue-500/10",
    },
    {
        "id": "JIRA",
        "name": "Jira Software",
        "category": "Support",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Create bug reports, support incident tickets, and query issue status from customer voice reports.",
        "actions": ["Create Issue", "Get Issue Details", "Add Comment"],
        "badge": "DevOps",
        "iconName": "GitBranch",
        "color": "text-blue-600 bg-blue-600/10",
    },
    {
        "id": "LINEAR",
        "name": "Linear",
        "category": "Support",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Search open customer feature requests and file urgent customer-reported issues directly to engineering.",
        "actions": ["Create Issue", "Search Issues", "Update Issue State"],
        "badge": "Fast",
        "iconName": "GitBranch",
        "color": "text-indigo-500 bg-indigo-500/10",
    },
    {
        "id": "FRESHDESK",
        "name": "Freshdesk",
        "category": "Support",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "api_key",
        "description": "Look up customer support tickets, verify SLA priority, and log call resolutions.",
        "actions": ["Lookup Tickets", "Create Ticket", "Add Note"],
        "badge": "Support",
        "iconName": "LifeBuoy",
        "color": "text-teal-600 bg-teal-600/10",
    },

    # --- 4. E-COMMERCE & PAYMENTS ---
    {
        "id": "SHOPIFY",
        "name": "Shopify",
        "category": "E-Commerce",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "api_key",
        "description": "Looks up live order status, tracking numbers, and delivery dates in real-time during phone calls.",
        "actions": ["Lookup Order by Phone", "Get Fulfillment Tracking", "Cancel Unfulfilled Order"],
        "badge": "Popular",
        "iconName": "ShoppingBag",
        "color": "text-pink-500 bg-pink-500/10",
    },
    {
        "id": "WOOCOMMERCE",
        "name": "WooCommerce",
        "category": "E-Commerce",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "api_key",
        "description": "Check WordPress store inventory stock, look up customer orders, and update shipping details.",
        "actions": ["Get Order Details", "Check Product Stock", "Update Order Status"],
        "badge": "Retail",
        "iconName": "ShoppingBag",
        "color": "text-purple-600 bg-purple-600/10",
    },
    {
        "id": "STRIPE",
        "name": "Stripe Billing",
        "category": "E-Commerce",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "api_key",
        "description": "Verify customer subscription status, lookup past invoice charges, and issue payment links on call.",
        "actions": ["Lookup Customer Charges", "Check Subscription Status", "Create Payment Link"],
        "badge": "Payments",
        "iconName": "CreditCard",
        "color": "text-indigo-600 bg-indigo-600/10",
    },

    # --- 5. TEAM COMMUNICATION & ALERTS ---
    {
        "id": "SLACK",
        "name": "Slack Alerts",
        "category": "Communication",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Post instant call summaries, emergency transfers, and audio recordings to team channels.",
        "actions": ["Send Channel Message", "Notify On-Call Rep", "Upload Call Summary"],
        "badge": "Popular",
        "iconName": "MessageSquare",
        "color": "text-purple-600 bg-purple-600/10",
    },
    {
        "id": "TWILIO_SMS",
        "name": "Twilio SMS",
        "category": "Communication",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "api_key",
        "description": "Send instant SMS confirmations, booking links, or product brochures to the caller's phone number.",
        "actions": ["Send SMS", "Send WhatsApp Confirmation", "Check Message Status"],
        "badge": "SMS",
        "iconName": "MessageSquare",
        "color": "text-red-500 bg-red-500/10",
    },
    {
        "id": "WHATSAPP",
        "name": "WhatsApp Business",
        "category": "Communication",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "api_key",
        "description": "Send automated WhatsApp follow-ups, payment links, and booking confirmations to callers.",
        "actions": ["Send Template Message", "Send Document Link", "Send Quick Reply"],
        "badge": "Popular",
        "iconName": "MessageSquare",
        "color": "text-emerald-500 bg-emerald-500/10",
    },
    {
        "id": "DISCORD",
        "name": "Discord",
        "category": "Communication",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "api_key",
        "description": "Post community support call logs and inbound lead notifications to staff channels.",
        "actions": ["Send Channel Message", "Post Lead Embed", "Alert Moderators"],
        "badge": "Community",
        "iconName": "MessageSquare",
        "color": "text-indigo-500 bg-indigo-500/10",
    },

    # --- 6. EMAIL FOLLOW-UPS ---
    {
        "id": "GMAIL",
        "name": "Gmail Follow-Up",
        "category": "Email",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Send automated personalized follow-up emails and meeting invites right after hanging up.",
        "actions": ["Send Follow-Up Email", "Create Email Draft", "Search Thread History"],
        "badge": "Popular",
        "iconName": "Mail",
        "color": "text-red-500 bg-red-500/10",
    },
    {
        "id": "SENDGRID",
        "name": "SendGrid",
        "category": "Email",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "api_key",
        "description": "Trigger high-deliverability transactional email summaries, receipts, and confirmations to callers.",
        "actions": ["Send Transactional Email", "Send Template Email", "Add Recipient to List"],
        "badge": "Transactional",
        "iconName": "Mail",
        "color": "text-blue-500 bg-blue-500/10",
    },
    {
        "id": "MAILCHIMP",
        "name": "Mailchimp",
        "category": "Email",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Add qualified callers to email newsletter lists and tag marketing interest based on call intent.",
        "actions": ["Add Member to Audience", "Tag Subscriber", "Trigger Email Campaign"],
        "badge": "Marketing",
        "iconName": "Mail",
        "color": "text-amber-500 bg-amber-500/10",
    },

    # --- 7. DATABASES & SPREADSHEETS ---
    {
        "id": "AIRTABLE",
        "name": "Airtable",
        "category": "Database",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "oauth",
        "description": "Query caller records from custom Airtable bases and append structured call logs in real time.",
        "actions": ["Search Record by Phone", "Create Record", "Update Field"],
        "badge": "Popular",
        "iconName": "Database",
        "color": "text-yellow-500 bg-yellow-500/10",
    },
    {
        "id": "NOTION",
        "name": "Notion",
        "category": "Database",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Search internal company knowledge bases and append call notes into Notion databases.",
        "actions": ["Search Database", "Create Page", "Append Call Notes"],
        "badge": "Docs",
        "iconName": "Layers",
        "color": "text-stone-800 bg-stone-800/10",
    },
    {
        "id": "SUPABASE",
        "name": "Supabase",
        "category": "Database",
        "timing": "in_call",
        "timing_label": "Live In-Call",
        "auth_type": "api_key",
        "description": "Query customer Postgres tables and insert structured call transcripts directly into your database.",
        "actions": ["Execute Query", "Insert Call Record", "Update User Row"],
        "badge": "Postgres",
        "iconName": "Database",
        "color": "text-emerald-500 bg-emerald-500/10",
    },

    # --- 8. OPERATIONS & TASK MANAGEMENT ---
    {
        "id": "ASANA",
        "name": "Asana Tasks",
        "category": "Productivity",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Create follow-up tasks for team members with call summaries, deadlines, and project tags.",
        "actions": ["Create Task", "Assign to Team Member", "Add Task Comment"],
        "badge": "Tasks",
        "iconName": "Sliders",
        "color": "text-rose-500 bg-rose-500/10",
    },
    {
        "id": "CLICKUP",
        "name": "ClickUp",
        "category": "Productivity",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Create action tasks with priority and assign them to account managers after call completes.",
        "actions": ["Create Task", "Set Priority", "Add Task Checklist"],
        "badge": "Productivity",
        "iconName": "Sliders",
        "color": "text-purple-600 bg-purple-600/10",
    },
    {
        "id": "MONDAY",
        "name": "Monday.com",
        "category": "Productivity",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Add leads and post-call action items to Monday board workflows automatically.",
        "actions": ["Create Item", "Update Column Value", "Add Board Update"],
        "badge": "Operations",
        "iconName": "Sliders",
        "color": "text-amber-500 bg-amber-500/10",
    },
    {
        "id": "TODOIST",
        "name": "Todoist",
        "category": "Productivity",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "Add quick follow-up reminders to the operator's personal or team task list.",
        "actions": ["Quick Add Task", "Set Due Date", "Add Task Label"],
        "badge": "Tasks",
        "iconName": "Sliders",
        "color": "text-red-500 bg-red-500/10",
    },
    {
        "id": "GITHUB",
        "name": "GitHub",
        "category": "Productivity",
        "timing": "post_call",
        "timing_label": "Async Post-Call",
        "auth_type": "oauth",
        "description": "File issue reports and log technical feedback from customer calls directly to repos.",
        "actions": ["Create Issue", "Add Label", "Comment on Issue"],
        "badge": "Dev",
        "iconName": "GitBranch",
        "color": "text-gray-900 bg-gray-900/10",
    },
]
