# One-time Cloudflare named tunnel for hustlelabs.in (stable api-dev / app-dev URLs)
# Prerequisite: hustlelabs.in must be added to your Cloudflare account (DNS on Cloudflare).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/setup_cloudflare_tunnel.ps1
#   powershell -ExecutionPolicy Bypass -File scripts/setup_cloudflare_tunnel.ps1 -LoginOnly
#   powershell -ExecutionPolicy Bypass -File scripts/run_cloudflare_tunnel.ps1

param(
    [switch]$LoginOnly,
    [string]$TunnelName = "voice-agent-dev",
    [string]$ApiHost = "api-dev.hustlelabs.in",
    [string]$AppHost = "app-dev.hustlelabs.in",
    [int]$ApiPort = 8000,
    [int]$AppPort = 3000
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$CloudflaredDir = Join-Path $env:USERPROFILE ".cloudflared"
$CertFile = Join-Path $CloudflaredDir "cert.pem"
$ConfigDir = Join-Path $RepoRoot "cloudflared"
$ConfigFile = Join-Path $ConfigDir "config.yml"
$EnvFile = Join-Path $RepoRoot ".env"

if (-not (Get-Command cloudflared -ErrorAction SilentlyContinue)) {
    Write-Error "Install cloudflared: winget install Cloudflare.cloudflared"
}

function Ensure-Login {
    if (Test-Path $CertFile) {
        Write-Host "Cloudflare login: OK ($CertFile)"
        return
    }
    Write-Host ""
    Write-Host "=== Cloudflare login required ==="
    Write-Host "A browser window will open. Log in and authorize hustlelabs.in."
    Write-Host "If it does not open, copy the URL printed by cloudflared."
    Write-Host ""
    & cloudflared tunnel login
    if (-not (Test-Path $CertFile)) {
        Write-Error "Login did not complete. Run again after authorizing in the browser."
    }
}

Ensure-Login
if ($LoginOnly) { exit 0 }

# Create tunnel if missing
$existing = & cloudflared tunnel list 2>&1 | Out-String
$tunnelId = $null
if ($existing -match "(?m)^[0-9a-f-]{36}\s+$([regex]::Escape($TunnelName))\s") {
    $tunnelId = ($existing | Select-String -Pattern "([0-9a-f-]{36})\s+$TunnelName" | ForEach-Object { $_.Matches[0].Groups[1].Value } | Select-Object -First 1)
    Write-Host "Tunnel '$TunnelName' already exists: $tunnelId"
} else {
    Write-Host "Creating tunnel '$TunnelName'..."
    $createOut = & cloudflared tunnel create $TunnelName 2>&1 | Out-String
    Write-Host $createOut
    if ($createOut -match "([0-9a-f-]{36})") {
        $tunnelId = $Matches[1]
    }
    if (-not $tunnelId) {
        $list = & cloudflared tunnel list 2>&1 | Out-String
        if ($list -match "(?m)^([0-9a-f-]{36})\s+$([regex]::Escape($TunnelName))") {
            $tunnelId = $Matches[1]
        }
    }
}
if (-not $tunnelId) {
    Write-Error "Could not create or find tunnel '$TunnelName'. Is hustlelabs.in on Cloudflare?"
}

$credFile = Join-Path $CloudflaredDir "$tunnelId.json"
if (-not (Test-Path $credFile)) {
    Write-Error "Credentials file missing: $credFile"
}

# DNS routes (idempotent — safe to re-run)
Write-Host "Routing DNS: $ApiHost"
$null = & cloudflared tunnel route dns $TunnelName $ApiHost 2>&1
Write-Host "Routing DNS: $AppHost"
$null = & cloudflared tunnel route dns $TunnelName $AppHost 2>&1

# Write config.yml
if (-not (Test-Path $ConfigDir)) { New-Item -ItemType Directory -Path $ConfigDir | Out-Null }
$config = @"
# Generated by scripts/setup_cloudflare_tunnel.ps1 — do not commit credentials
tunnel: $tunnelId
credentials-file: $($credFile -replace '\\','/')

ingress:
  - hostname: $ApiHost
    service: http://127.0.0.1:$ApiPort
  - hostname: $AppHost
    service: http://127.0.0.1:$AppPort
  - service: http_status:404
"@
Set-Content -Path $ConfigFile -Value $config.TrimEnd()
Write-Host "Wrote $ConfigFile"

# Update .env for webhooks
$publicApi = "https://$ApiHost"
if (Test-Path $EnvFile) {
    $lines = Get-Content $EnvFile
    $map = @{
        "PUBLIC_TUNNEL_URL"      = $publicApi
        "PLIVO_WEBHOOK_BASE_URL" = $publicApi
        "PLIVO_PUBLIC_BASE_URL"  = $publicApi
        "CLIENT_URL"             = "https://$AppHost"
    }
    foreach ($key in $map.Keys) {
        $val = $map[$key]
        $found = $false
        for ($j = 0; $j -lt $lines.Count; $j++) {
            if ($lines[$j] -match "^$key=") {
                $lines[$j] = "$key=$val"
                $found = $true
                break
            }
        }
        if (-not $found) { $lines += "$key=$val" }
    }
    Set-Content -Path $EnvFile -Value $lines
    Write-Host "Updated .env (PUBLIC_TUNNEL_URL, PLIVO_*, CLIENT_URL)."
}

# web/.env.local for stable public API when testing from browser
$webEnv = Join-Path $RepoRoot "web\.env.local"
$webLines = @(
    "NEXT_PUBLIC_API_URL=$publicApi",
    "API_INTERNAL_URL=http://127.0.0.1:$ApiPort"
)
Set-Content -Path $webEnv -Value ($webLines -join "`n")
Write-Host "Updated web/.env.local → $publicApi"

Write-Host ""
Write-Host "=== Cloudflare tunnel ready ==="
Write-Host "Stable API:  https://$ApiHost"
Write-Host "Stable App:  https://$AppHost"
Write-Host "Answer URL:  https://$ApiHost/api/plivo/answer"
Write-Host ""
Write-Host "Start stack:  npm run dev:up -KillStale"
Write-Host "Start tunnel: npm run dev:cf-tunnel"
Write-Host "Or both:      powershell -File scripts/dev_local_full.ps1 -Tunnel cloudflare-named"
